# Generated by Django 5.0.4 on 2024-05-05 15:34

import sorl.thumbnail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=140)),
                ('image', sorl.thumbnail.fields.ImageField(upload_to='')),
            ],
        ),
    ]
